package InterfaceComponents;

import RoverUI.Vehicle.Truck;
import RoverUI.Vehicle.Wheel;

public class TruckEngager extends javax.swing.JPanel {
    Truck mTruck;

    /**
     * Creates new form TruckEngager
     */
    public TruckEngager() {
        initComponents();
    }

    public void setTruck(Truck truck) {
        mTruck = truck;
        WheelEngager[] enagers = new WheelEngager[]{
                mWheelEngager1, mWheelEngager2,
                mWheelEngager3, mWheelEngager4
        };
        Wheel[] wheels = mTruck.getWheels();

        for (int i = 0; i < 4; i++) {
            Wheel wheel = wheels[i];
            enagers[i].setWheel(wheel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mWheelEngager1 = new InterfaceComponents.WheelEngager();
        mWheelEngager2 = new InterfaceComponents.WheelEngager();
        mWheelEngager3 = new InterfaceComponents.WheelEngager();
        mWheelEngager4 = new InterfaceComponents.WheelEngager();

        setLayout(new java.awt.GridLayout(2, 2, 0, 50));
        add(mWheelEngager1);
        add(mWheelEngager2);
        add(mWheelEngager3);
        add(mWheelEngager4);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private InterfaceComponents.WheelEngager mWheelEngager1;
    private InterfaceComponents.WheelEngager mWheelEngager2;
    private InterfaceComponents.WheelEngager mWheelEngager3;
    private InterfaceComponents.WheelEngager mWheelEngager4;
    // End of variables declaration//GEN-END:variables
}
