package RoverUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;

public class DeviceListItem extends javax.swing.JPanel {
    public static abstract class ListItemActionListener 
            implements  ActionListener, FocusListener {

    }
    
    private String mChannelName;
    
    public DeviceListItem() {
        initComponents();
    }
    
    public DeviceListItem(String channelName) {
        initComponents();
        mCheckBox.setText(channelName);
    }
    
    public void addActionListener(ListItemActionListener al) {
        mCheckBox.addActionListener(al);
        mTextMultiplier.addActionListener(al);
        mTextMultiplier.addFocusListener(al);
    }
    
    public boolean isSelected() {
        return mCheckBox.isSelected();
    }
    
    public void setSelected(boolean value) {
        mCheckBox.setSelected(value);
    }
    
    public double getMultiplier() {
        return Double.parseDouble(mTextMultiplier.getText());
    }
    
    public void setMultiplier(double multiplier) {
        mTextMultiplier.setText(String.format("%.3f", multiplier));
    }
    
    public void setStatus(String status) {
        mLableStatus.setText(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mCheckBox = new javax.swing.JCheckBox();
        mLabelMultiplier = new javax.swing.JLabel();
        mTextMultiplier = new javax.swing.JTextField();
        mLableStatus = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(200, 100));
        setMinimumSize(new java.awt.Dimension(417, 200));
        setPreferredSize(new java.awt.Dimension(400, 100));
        setLayout(new java.awt.GridBagLayout());

        mCheckBox.setText("jCheckBox1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(mCheckBox, gridBagConstraints);

        mLabelMultiplier.setText("Multiplier");
        mLabelMultiplier.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(mLabelMultiplier, gridBagConstraints);

        mTextMultiplier.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mTextMultiplier.setText("1.000");
        mTextMultiplier.setAlignmentY(0.0F);
        mTextMultiplier.setMinimumSize(new java.awt.Dimension(100, 10));
        mTextMultiplier.setPreferredSize(new java.awt.Dimension(100, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(mTextMultiplier, gridBagConstraints);

        mLableStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mLableStatus.setText("Status");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(mLableStatus, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox mCheckBox;
    private javax.swing.JLabel mLabelMultiplier;
    private javax.swing.JLabel mLableStatus;
    private javax.swing.JTextField mTextMultiplier;
    // End of variables declaration//GEN-END:variables
}
