package RoverUI;

import RoverUI.Vehicle.DeviceInfo;

import javax.swing.*;

public class DeviceEngager extends javax.swing.JPanel implements DeviceInfo.ChangeListener {
    private DeviceInfo mDeviceInfo;
    private Boolean mEngaged = null;

    /**
     * Creates new form DevicelEngager
     */
    public DeviceEngager() {
        initComponents();
        clearStatus();
    }

    public void setDeviceInfo(DeviceInfo deviceInfo) {
        mDeviceInfo = deviceInfo;
        mDeviceInfo.addChangeListener(this);
        updateInfoLater();
    }

    public void updateInfoLater() {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                updateInfo();
            }
        });
    }

    public void updateInfo() {
        mLblHeading.setText("<html><b>" + mDeviceInfo.getName() + "</b></html>");
        mLblInfo.setText("<html><div style=\"width:100px\">" + mDeviceInfo.getParamsInfoString().replace("\n", "<br>") + "</div></html>");
        mEngaged = mDeviceInfo.getEngaged();
        mLblStatus.setText("Status: " + mDeviceInfo.getEngageStatus().getName());
        if (mEngaged != null) {
            mBtnEngager.setText(mEngaged ? "Disengage" : "Engage");
            mBtnEngager.setEnabled(true);
            if (mDeviceInfo.getIsReEngaging()) {
                mBtnReEngage.setText("reEngaging");
                mBtnReEngage.setEnabled(false);
            } else {
                mBtnReEngage.setText("reEngage");
                mBtnReEngage.setEnabled(true);
            }
        } else {
            clearStatus();
        }
    }

    public final void clearStatus() {
        mBtnEngager.setText("(Dis/-)engage");
        mBtnEngager.setEnabled(false);
        mBtnReEngage.setEnabled(false);
        mLblStatus.setText("Status: Unknown");
    }

    @Override
    public void onEngage(DeviceInfo deviceInfo, boolean engaged) {
        mEngaged = engaged;
        updateInfoLater();
    }


    @Override
    public void onParamChange(DeviceInfo deviceInfo, String paramName) {
        updateInfoLater();
    }

    public void setEngaged(boolean value) {
        mBtnEngager.setText(!value ? "Disenging" : "Engaging");
        mBtnEngager.setEnabled(false);
        mDeviceInfo.requestToSetEngaged(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mLblHeading = new javax.swing.JLabel();
        mLblInfo = new javax.swing.JLabel();
        mLblStatus = new javax.swing.JLabel();
        mBtnEngager = new javax.swing.JButton();
        mBtnReEngage = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        mLblHeading.setText("<Device Name>");
        add(mLblHeading);

        mLblInfo.setText("<Info>");
        mLblInfo.setAutoscrolls(true);
        add(mLblInfo);

        mLblStatus.setText("Status: <None>");
        add(mLblStatus);

        mBtnEngager.setText("(Dis/-)engage");
        mBtnEngager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBtnEngagerActionPerformed(evt);
            }
        });
        add(mBtnEngager);

        mBtnReEngage.setText("reEngage");
        mBtnReEngage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBtnReEngageActionPerformed(evt);
            }
        });
        add(mBtnReEngage);
    }// </editor-fold>//GEN-END:initComponents

    private void mBtnEngagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBtnEngagerActionPerformed
        setEngaged(!mEngaged);
    }//GEN-LAST:event_mBtnEngagerActionPerformed

    private void mBtnReEngageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBtnReEngageActionPerformed
        mBtnReEngage.setEnabled(false);
        mBtnReEngage.setText("reEngaging");
        mDeviceInfo.requestToReEngage();
    }//GEN-LAST:event_mBtnReEngageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mBtnEngager;
    private javax.swing.JButton mBtnReEngage;
    private javax.swing.JLabel mLblHeading;
    private javax.swing.JLabel mLblInfo;
    private javax.swing.JLabel mLblStatus;
    // End of variables declaration//GEN-END:variables


}
